// <auto-generated />
namespace ERPortal.WebUI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ga : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ga));
        
        string IMigrationMetadata.Id
        {
            get { return "202003110515471_ga"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
