// <auto-generated />
namespace ERPortal.DataAccess.SQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class ERTechniqueColAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ERTechniqueColAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202004071235518_ERTechniqueColAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
